image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - release

variables:
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_NIGHTLY_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $CONTAINER_NIGHTLY_IMAGE .
    - docker push $CONTAINER_NIGHTLY_IMAGE

test-sample:
  stage: test
  script:
    - docker pull $CONTAINER_NIGHTLY_IMAGE
    - docker run --volume "$(pwd):/workdir" $CONTAINER_NIGHTLY_IMAGE latexmk -pdfdvi sample.tex

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_NIGHTLY_IMAGE
    - docker tag $CONTAINER_NIGHTLY_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
