version: "3.9"

services:
  sut-basic:
    build:
      context: .
      target: basic
    volumes:
    - ./example/basic:/workdir
    command: pdflatex sample.tex

  sut-full:
    build:
      context: .
      target: full
    volumes:
    - ./example/full:/workdir
    command: latexmk sample.tex
