name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pull required images
        run: |
          docker-compose --file docker-compose.test.yml pull

      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Run build
        run: |
          docker-compose --file docker-compose.test.yml build

      - name: Run core test
        run: |
          docker-compose --file docker-compose.test.yml run sut-core
      - name: Run full test
        run: |
          docker-compose --file docker-compose.test.yml run sut-full

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}

      -
        name: Build and push core
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: core
          tags: docker.pkg.github.com/${{ github.repository }}/core:latest

      -
        name: Build and push full
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: full
          tags: docker.pkg.github.com/${{ github.repository }}/full:latest
