name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull required images
        run: |
          docker compose --file docker-compose.test.yml pull

      - name: Run build
        run: |
          docker compose --file docker-compose.test.yml build

      - name: Run basic test
        run: |
          docker compose --file docker-compose.test.yml run sut-basic
      - name: Run full test
        run: |
          docker compose --file docker-compose.test.yml run sut-full

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      -
        name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      -
        name: Build and push basic
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: basic
          tags: ghcr.io/${{ github.repository }}:minimal

      -
        name: Build and push full
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          target: full
          tags: ghcr.io/${{ github.repository }}:latest
